/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Exact Figma Site Color Palette
        'figma-cream-lightest': '#faf9f7',
        'figma-text-dark': '#2d2d2d',
        'figma-cream-light': '#f5f4f2',
        'figma-cream': '#ede9e3',
        'figma-gray-medium': '#4a4a4a',
        'figma-gray': '#6b6b6b',
        'figma-beige-light': '#e8e4de',
        'figma-brown-accent': '#8b4513',
        'figma-cream-warm': '#f0ede7',
        'figma-beige': '#d4d0c8',
        'figma-sage-green': '#7d8471',
        'figma-tan': '#8b7355',
        'figma-gray-warm': '#8b8680',
        'figma-gold': '#a0926b',
        'figma-green-sage': '#9ca986',
        'figma-black-dark': '#1a1a1a',
        'figma-black-medium': '#242424',
        'figma-black-light': '#2f2f2f',
        'figma-slate-blue': '#36454f',
        'figma-orange-accent': '#cd853f',
        'figma-black-soft': '#1f1f1f',
        'figma-gray-muted': '#a19b94',
        
        // OKOA Semantic Colors Based on Figma Palette
        'okoa-bg-primary': '#faf9f7',
        'okoa-bg-secondary': '#f5f4f2', 
        'okoa-bg-tertiary': '#ede9e3',
        'okoa-fg-primary': '#2d2d2d',
        'okoa-fg-secondary': '#4a4a4a',
        'okoa-fg-muted': '#6b6b6b',
        'okoa-accent-primary': '#8b4513',
        'okoa-accent-secondary': '#8b7355',
        'okoa-border-primary': '#d4d0c8',
        'okoa-border-secondary': '#e8e4de',
        
        // Japanese-inspired color names
        'japanese-paper-warm': '#faf9f7',
        'japanese-ink-light': '#e8e4de',
        'japanese-ink-sumi': '#1a1a1a',
        'japanese-neutral-warm-gray': '#a19b94',
        
        // Legacy support 
        white: '#faf9f7',
        black: '#2d2d2d',
        primary: {
          50: '#faf9f7',
          100: '#f5f4f2',
          600: '#4a4a4a',
          900: '#2d2d2d',
        },
        accent: {
          primary: '#8b4513',
          hover: '#8b7355',
        },
      },
      fontFamily: {
        'mono': ['ui-monospace', 'SF Mono', 'Monaco', 'Cascadia Code', 'Roboto Mono', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier New', 'monospace'],
        'sans': ['ui-monospace', 'SF Mono', 'Monaco', 'Cascadia Code', 'Roboto Mono', 'Consolas', 'Liberation Mono', 'Menlo', 'Courier New', 'monospace'],
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '1.4' }],
        'sm': ['14px', { lineHeight: '1.5' }],
        'base': ['14px', { lineHeight: '1.5' }],
        'lg': ['16px', { lineHeight: '1.5' }],
        'xl': ['18px', { lineHeight: '1.5' }],
        '2xl': ['20px', { lineHeight: '1.4' }],
        '3xl': ['24px', { lineHeight: '1.3' }],
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
      },
      borderRadius: {
        'none': '0px',
        'sm': '2px',
        'md': '4px',
        'lg': '6px',
      },
      borderWidth: {
        DEFAULT: '1px',
        '0': '0px',
        'thin': '1px',
        '2': '2px',
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        'md': '0 2px 4px -2px rgb(0 0 0 / 0.1), 0 4px 8px -2px rgb(0 0 0 / 0.1)',
        'lg': '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
      },
    },
  },
  plugins: [],
}